remote_theme: "mmistakes/minimal-mistakes@4.24.0"

plugins:
  - jekyll-sitemap
  - jekyll-include-cache

minimal_mistakes_skin: "aqua"
title: "Alex LaGrassa"
name: "Alex LaGrassa"
description: "personal website"
logo: /media/logo.png


# Social Sharing
twitter:
  username: alex_lagrassa




#Files 
include:
 - media


# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false


# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # https://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style


# Outputting
permalink: /:categories/:title/
paginate: 1 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: # true
      share: true
      related: true

# Site Settings
locale                   : "en-US"
title                    : "Alex LaGrassa"
title_separator          : "-"
subtitle                 : "personal website"
name                     : "Alex LaGrassa"
teaser                   : /media/logo.png
logo                     : /media/logo.png


# Site Author
author:
  name: "Alex LaGrassa"
  avatar: "/media/bio.jpg"
  bio: "Robotics PhD candidate interested in model-based planning with inaccurate models and sharing information with others about AI and robotics through hands-on learning."
  location         : "Pittsburgh, PA"
  email            : "lagrassa at cmu dot edu"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      # url: "mailto:lagrassa@cmu.edu"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      # url: "https://twitter.com/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      # url: "https://github.com/"

